//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyPhongKham.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHITIETBAOCAODOANHTHUTHANG
    {
        public int MaBaoCaoDoanhThuThang { get; set; }
        public int Ngay { get; set; }
        public Nullable<int> SoBenhNhan { get; set; }
        public Nullable<double> DoanhThu { get; set; }
        public Nullable<double> TyLe { get; set; }
    
        public virtual BAOCAODOANHTHUTHANG BAOCAODOANHTHUTHANG { get; set; }
    }
}
