//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyPhongKham.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHIEUKHAM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PHIEUKHAM()
        {
            this.CHITIETDICHVUs = new HashSet<CHITIETDICHVU>();
            this.DONTHUOCs = new HashSet<DONTHUOC>();
            this.HANGCHOTHANHTOANs = new HashSet<HANGCHOTHANHTOAN>();
            this.HANGSUDUNGDICHVUs = new HashSet<HANGSUDUNGDICHVU>();
            this.HOADONs = new HashSet<HOADON>();
        }
    
        public int MaPhieuKham { get; set; }
        public Nullable<System.DateTime> NgayKham { get; set; }
        public int MaBenhNhan { get; set; }
        public string TrieuChung { get; set; }
        public int MaLoaiBenh { get; set; }
        public Nullable<System.DateTime> NgayTaiKham { get; set; }
        public Nullable<bool> DaBanThuoc { get; set; }
    
        public virtual BENHNHAN BENHNHAN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETDICHVU> CHITIETDICHVUs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DONTHUOC> DONTHUOCs { get; set; }
        public virtual HANGCHOKHAMBENH HANGCHOKHAMBENH { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HANGCHOTHANHTOAN> HANGCHOTHANHTOANs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HANGSUDUNGDICHVU> HANGSUDUNGDICHVUs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HOADON> HOADONs { get; set; }
        public virtual LOAIBENH LOAIBENH { get; set; }
    }
}
